version: '2'
services:
  web:
    build:
      context: .
      args:
        - env=development
    command: ['npm', 'run', 'devstart']
    ports:
      - 8100:8100
    volumes:
      - .:/opt/apps/profiles-service
