const sprintf = require('sprintf');
const headers = 'Previews Code,Quantity,Title,Price,Publisher,Comment\n';
const row = '%s,%d,%s,%s,%s,%s\n';

module.exports = (req, res, next) => {
  let order = undefined;

  if (!req.body.encodeddata) {
    var err = new Error('No form data found');
    err.status = 400;

    return next(err);
  }

  try {
    order = JSON.parse(req.body.encodeddata);
  } catch (err) {
    let error = new Error('Malformed request');
    error.status = 400;
    return next({ status: 400, message: "Invalid request"});
  }

  if (!order.line_items || !order.line_items.length) {
    let error = new Error('Malformed order');
    error.status = 422;

    return next(error);
  }

  let csv = headers;

  for (let i = 0; i < order.line_items.length; i++) {
    const lineItem = order.line_items[i];
    csv += sprintf(row, lineItem.previews,
                          lineItem.quantity,
                          lineItem.title,
                          lineItem.price,
                          lineItem.publisher,
                          lineItem.comment);
  }

  csv += ",,Total," + (order.order_total / 100) + ",\n";
  csv += "\nGenerated by Ace My Order";

  res.setHeader("Content-type", "text/csv");
  res.setHeader("Content-Disposition", "filename=order" + order.issue + ".csv");
  res.setHeader("Pragma", "no-cache");
  res.setHeader("Expires", "0");
  res.send(csv);
}
